name: sharenchat
description: A new Flutter project.
publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=2.18.5 <3.0.0'


dependencies:
  flutter:
    sdk: flutter



  cupertino_icons: 1.0.5
  firebase_core: 1.21.1
  firebase_auth: 3.7.0
  google_sign_in: 5.4.1
  cloud_firestore:  3.4.6
  fluttertoast: 8.0.9
  image_picker: 0.8.5+3
  shared_preferences: 2.0.15
  firebase_storage: 10.3.7
  firebase_messaging: 13.0.0
  flutter_local_notifications: 9.8.0+1
  photo_view: 0.14.0
  provider: ^6.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^2.0.0

dependency_overrides: 
  firebase_auth_platform_interface: 6.7.0
  firebase_core_platform_interface: 4.5.1
flutter:

  
  
  uses-material-design: true

  assets:
    - images/

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
